run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  gofumpt:
    extra-rules: true
  misspell:
    locale: US
