version: 2

builds:
  - main: .
    binary: puzzletea
    ldflags:
      - -s -w -X github.com/FelineStateMachine/puzzletea/cmd.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - name: puzzletea
    homepage: "https://github.com/FelineStateMachine/puzzletea"
    description: "Terminal-based puzzle game collection built with Bubble Tea"
    repository:
      owner: FelineStateMachine
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Update {{ .ProjectName }} to {{ .Tag }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/puzzletea"]
          end

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
